name: Node.js CI

on:
  push:
    branches: [main, dev/*]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Deploy Stage
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.netlify.com/build_hooks/61a8763f58965ea893647b4c'
        method: 'POST'
